/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const PlayerState = IDL.Record({
  'ammo' : IDL.Nat,
  'isAlive' : IDL.Bool,
  'position' : Position,
  'currentWeapon' : IDL.Text,
  'health' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text], [], []),
  'endSession' : IDL.Func([IDL.Text], [], []),
  'getPlayerState' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [PlayerState],
      ['query'],
    ),
  'getSessionStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Text], [], []),
  'pickUpWeapon' : IDL.Func([IDL.Text, IDL.Text, Position], [], []),
  'respawnPlayer' : IDL.Func([IDL.Text], [], []),
  'shootPlayer' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
  'updatePlayerPosition' : IDL.Func([IDL.Text, Position], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const PlayerState = IDL.Record({
    'ammo' : IDL.Nat,
    'isAlive' : IDL.Bool,
    'position' : Position,
    'currentWeapon' : IDL.Text,
    'health' : IDL.Nat,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text], [], []),
    'endSession' : IDL.Func([IDL.Text], [], []),
    'getPlayerState' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [PlayerState],
        ['query'],
      ),
    'getSessionStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Text], [], []),
    'pickUpWeapon' : IDL.Func([IDL.Text, IDL.Text, Position], [], []),
    'respawnPlayer' : IDL.Func([IDL.Text], [], []),
    'shootPlayer' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
    'updatePlayerPosition' : IDL.Func([IDL.Text, Position], [], []),
  });
};

export const init = ({ IDL }) => { return []; };