/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerState {
  'ammo' : bigint,
  'isAlive' : boolean,
  'position' : Position,
  'currentWeapon' : string,
  'health' : bigint,
}
export interface Position { 'x' : number, 'y' : number, 'z' : number }
export interface _SERVICE {
  'createSession' : ActorMethod<[string], undefined>,
  'endSession' : ActorMethod<[string], undefined>,
  'getPlayerState' : ActorMethod<[string, Principal], PlayerState>,
  'getSessionStatus' : ActorMethod<[string], boolean>,
  'joinSession' : ActorMethod<[string], undefined>,
  'pickUpWeapon' : ActorMethod<[string, string, Position], undefined>,
  'respawnPlayer' : ActorMethod<[string], undefined>,
  'shootPlayer' : ActorMethod<[string, Principal], boolean>,
  'updatePlayerPosition' : ActorMethod<[string, Position], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];